version: '3'

services:
  db:
    container_name: adv_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=adv_postgres
      - POSTGRES_PORT=3306
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=advertisement_campaigns
      - PGDATA=/var/lib/postgresql/data/adv
      - PGUSER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/adv

  queue:
    container_name: adv_redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  app:
    image: node:20
    restart: unless-stopped
    working_dir: /app
    tty: true
    command: bash -c "npm i && npm start"
    network_mode: 'host'
    volumes:
      - ../src:/app/src
      - ../.env:/app/.env
      - ../package.json:/app/package.json
      - ../node_modules:/app/node_modules
      - ../nest-cli.json:/app/nest-cli.json
      - ../tsconfig.build.json:/app/tsconfig.build.json
      - ../tsconfig.json:/app/tsconfig.json
    depends_on:
      - db
      - queue
